# Generated by Django 4.0.5 on 2023-03-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Branch name')),
                ('position_latitude', models.FloatField()),
                ('position_longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Catigoris name')),
                ('catigoris_position', models.PositiveSmallIntegerField(verbose_name='position for catigoris')),
                ('images', models.ImageField(upload_to='menu_img/')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('language_code', models.CharField(default='uz ', help_text='Foydalanuvchining qurilmadagi tili.', max_length=8)),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(blank=True, max_length=10, null=True, verbose_name='Holati')),
                ('action_item', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Holat qiymati')),
                ('locations', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tovarning ismi')),
                ('image', models.ImageField(upload_to='product_img/')),
                ('price', models.PositiveIntegerField(verbose_name='narx')),
                ('description', models.TextField()),
                ('position', models.PositiveSmallIntegerField(verbose_name='tovarning pozitsiyasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.menu')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='telefon nomer')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('Naxt', 'Naxt'), ('Click', 'Click'), ('PayMe', 'PayMe'), ('Terminal', 'Terminal')], default='Naxt', max_length=10, verbose_name="To'lov turlari")),
                ('states', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('preparing', 'preparing'), ('delivering', 'delivering'), ('accepted', 'accepted'), ('declined', 'declined'), ('archivad', 'archivad'), ('cancellation', 'cancellation')], max_length=12, verbose_name='buyurtmaning holati')),
                ('all_price', models.PositiveBigIntegerField(default=0, verbose_name="to'plam narx")),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('add_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.order')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
    ]
